version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-currency
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
